### ISSUE TITLE
colab or huggingface demo

### ISSUE THREAD

**Issue by loboere** [xuehy/HiFiFace-pytorch#1]
colab or huggingface demo
you can add a local or a hugginface demo

**Comment by loboere** [comment]
the huggingface demo doesn't work with almost any image

**Comment by xuehy** [comment]
> the huggingface demo doesn't work with almost any image

It works fine as
![image](https://github.com/xuehy/HiFiFace-pytorch/assets/2055701/06b5f21c-dde1-4ae2-b363-ac39b1d934d3)

You can check if your images are correct or send me your images for test.

**Comment by 123456klk1** [comment]
hi!  You are doing so well, I can't wait to learn about your work, why can't I run successfully?

![image](https://github.com/xuehy/HiFiFace-pytorch/assets/53042912/58d805ba-45d4-4281-8b48-8d749d0317a6)

**Comment by xuehy** [comment]
> hi! You are doing so well, I can't wait to learn about your work, why can't I run successfully?
> 
> ![image](https://private-user-images.githubusercontent.com/53042912/298284902-58d805ba-45d4-4281-8b48-8d749d0317a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTI3NDMsIm5iZiI6MTcwNjQ5MjQ0MywicGF0aCI6Ii81MzA0MjkxMi8yOTgyODQ5MDItNThkODA1YmEtNDVkNC00MjgxLThiNDgtOGQ3NDlkMDMxN2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAxNDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZWU5NTc2MWEzN2ViM2EzODk5NjE4YzZlNzcyZDc0NGNmMTA2YzNkZTY0ZjRmMzZhNGI4MTJkZDM1MDJhNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xujum1d4AqupvmmbSEGUFjZEEm0Su20fNfqypyGKP04)

It has been restarted.

**Comment by emnab** [comment]
<img width="1917" height="422" alt="Image" src="https://github.com/user-attachments/assets/57a5d091-97a7-48e9-b8bf-0306a0dd0915" />
